language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - bison
           - libstdc++-5-dev

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
