version: ~> 1.0

language: generic

dist: precise

install:
 - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
 - aws sts get-caller-identity
 - source utils/toolchain.sh

script:
 - if [ ! ${MASON_NAME:-} ]; then ./test/all.sh; fi;
