language: generic

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - bison
           - flex
           - libstdc++-5-dev

script:
- CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.19.5/cmake-3.19.5-Linux-x86_64.tar.gz"
- mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
- export PATH=$(pwd)/cmake/bin:${PATH}
- cmake --version
- which cmake
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
