language: generic

env:
  global:
    - PYTHON=python3
matrix:
  include:
    - os: osx
      osx_image: xcode12.2
    - os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++-6-dev
           - xutils-dev
           - postgresql-9.5-postgis-2.4

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
